Block Harvestability Re-work
GTNewHorizons/NotEnoughIds pull request #4
Opened 2023-11-28 06:33 UTC by Cleptomania

This overwrites a number of methods added by Forge to the vanilla `Block` class.

Forge creates two arrays on every block, one which is an `int[16]` and one which is a `String[16]`. These are initialized to `-1` and `null` values as a default for every position in the array. The indexes of these arrays correspond to the possible block metadata values. This is, to say the least, horrible for memory usage, and does not scale to the eventual 16-bit metadata increase in NotEnoughIDs.

This replaces the above system with a class level default String and int for the harvest level and effective tool, while simultaneously creating a HashMap to each array. The hashmap by default has no values, and will only get values populated for the metadata it needs them for, done by calling the `setHarvestLevel` method with a metadata. If the metadata value is not present within the hashmap, then the class default is returned.

This maintains the exact same API that was provided by the public functions, while overwriting the internal private functionality, so there is unlikely to be any collision with these internal values. A class dump of the full GTNH pack shows no ASM collisions in this area.

I have tested in full pack with a few things, including GT tools and specifically with various tinker's tool materials against different ores to ensure that this doesn't hurt anything related to those. Everything still works as anticipated it just uses far less memory than before and helps paves the way for 16-bit metadata.

2023-11-28 06:58 UTC, bombcar commented
Loads and runs in the pack for me, I'll keep running with it and see what I can see.

Not much of a difference in the memory usage reported by F3 as far as I can tell, but that may be expected give that it's not expanded yet.

2023-11-28 07:40 UTC, Alexdoru requested changes

2023-11-28 07:40 UTC, Alexdoru commented on src/main/java/com/gtnewhorizons/neid/mixins/early/minecraft/MixinBlock.java
> +    private String defaultHarvestTool = null;
The mixin added fields needs to be annotated with @ Unique and the names prefixed with neid$

2023-11-28 07:40 UTC, Alexdoru commented on src/main/java/com/gtnewhorizons/neid/mixins/early/minecraft/MixinBlock.java
> +    public void setHarvestLevel(String toolClass, int level, int metadata) {
You should triple check with a class dump of your own that no mod is changing those methods

2023-11-28 07:48 UTC, Glease commented
vanilla have a max of 4096 block types, which correspond to 4096*16*8*2=1MB memory wasted even if none of them have any harvestiblity data. I don't see where you got that impression that this is horribly memory inefficient.

2023-11-28 08:26 UTC, Alexdoru commented
What happens with classes that extend the Block class and overrides one of those methods or use one of the fields you set to null ?

2023-11-28 11:10 UTC, Caedis commented
Started a brand new world and so far 0 issues

2023-11-28 14:21 UTC, Cleptomania commented
> What happens with classes that extend the Block class and overrides one of those methods or use one of the fields you set to null ?

The fields that were made null were private, so unless something is ASMing them or using reflection I don’t think it’s a concern. If something does override those functions they’d have to be doing someone completely unique anyways.

However, I have considered putting 16-bit metadata behind a config option, and this change is really intended to support that, so if this seems too invasive, we could close this and bring it in as part of the 16-bit metadata increase also behind that config option, it just worthwhile to test this broadly unrelated to the 16-bit metadata change.


> vanilla have a max of 4096 block types, which correspond to `4096*16*8*2=1MB` memory wasted even if none of them have any harvestiblity data. I don't see where you got that impression that this is horribly memory inefficient. surely it doesn't scale with 16bit meta, but it cannot be called a horrible choice for vanilla.

I was mostly referring to the scalability with the increased metadata that calculation becomes `32767 * 65536 * 12 = almost 26GB` with NEID after we increase the metadata later if we were to stick with the vanilla option.

2023-11-28 14:25 UTC, Alexdoru commented
> The fields that were made null were private, so unless something is ASMing them or using reflection I don’t think it’s a concern. If something does override those functions they’d have to be doing someone completely unique anyways.

access transformer go brrrrr

2023-12-04 19:10 UTC, boubou19 commented
@Cleptomania any news on this? the build doesn't pass

2023-12-04 19:22 UTC, Caedis commented
@boubou19 what do you mean? The build is passing

2023-12-04 20:17 UTC, boubou19 commented
wtf, i guess i was drunk

2023-12-18 02:05 UTC, Cleptomania commented
I'm going to go ahead and close this, as it's really only needed in conjunction with the 16-bit metadata increases that are coming Soon™. I will just pull these changes in with the rest of the metadata stuff.

2023-12-18 02:05 UTC, closed without merging